name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      # Step 3: Run Maven clean, test, and generate JaCoCo reports
      - name: Run tests and generate coverage report
        run: |
          mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report --quiet
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "Coverage report generated successfully."
          else
            echo "Coverage report not found. Failing the build."
            exit 1
          fi

      # Step 4: Calculate total coverage
      - name: Calculate and display total coverage
        run: |
          COVERAGE=$(grep -oP '(?<=<counter type="INSTRUCTION" missed=")\d+(?=.*>)' target/site/jacoco/jacoco.xml \
          | awk '{total+=1; covered+=$0} END {if (total > 0) print (covered/total)*100; else print 0}')
          echo "Total Coverage: $COVERAGE%"
          echo "Coverage calculation completed."

      # Step 5: Display detailed coverage report
      - name: Display coverage report
        run: cat target/site/jacoco/jacoco.xml || echo "No test report found."
