name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests and generate coverage report
        run: |
          mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report \
            --fail-at-end --batch-mode \
            -Dorg.slf4j.simpleLogger.defaultLogLevel=error \
            -Djava.util.logging.ConsoleHandler.level=SEVERE \
            -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env:
          MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

      - name: Display test results
        if: always()
        run: cat target/surefire-reports/*.txt || echo "No test report found."

      - name: Verify test coverage
        run: |
          if [ -f target/site/jacoco/jacoco.xml ]; then
            COVERAGE=$(grep -oP '(?<=<counter type="INSTRUCTION" missed=")\d+(?=.*>)' target/site/jacoco/jacoco.xml | awk '{total+=1; covered+=$0} END {print (covered/total)*100}')
            echo "Test coverage: $COVERAGE%"
            if (( $(echo "$COVERAGE < 80" | bc -l) )); then
              echo "Test coverage ($COVERAGE%) is below the threshold of 80%."
              exit 1
            else
              echo "Test coverage ($COVERAGE%) meets the threshold of 80%."
            fi
          else
            echo "Coverage report not found. Failing the build."
            exit 1
          fi