name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Run tests and generate coverage report
        run: |
          mvn -Dtest.quiet=true -Dmaven.test.redirectTestOutputToFile=true clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report --quiet
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "Coverage report generated successfully."
          else
            echo "Coverage report not found. Failing the build."
            exit 1
          fi

      - name: Display coverage report
        run: |
          echo "=== Coverage Report ==="
          echo "Type         Covered   Missed   Total    Coverage"
          echo "------------------------------------------------"

          cat target/site/jacoco/jacoco.xml | grep "<counter type=" | while read -r line; do
            TYPE=$(echo $line | grep -o 'type="[^"]*"' | cut -d'"' -f2)
            COVERED=$(echo $line | grep -o 'covered="[^"]*"' | cut -d'"' -f2)
            MISSED=$(echo $line | grep -o 'missed="[^"]*"' | cut -d'"' -f2)
            TOTAL=$((COVERED + MISSED))
            COVERAGE=$(echo "scale=2; 100 * $COVERED / $TOTAL" | bc)
            printf "%-12s %-9s %-9s %-9s %6.2f%%\n" "$TYPE" "$COVERED" "$MISSED" "$TOTAL" "$COVERAGE"
          done | sort | uniq