name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          fail-if-coverage-less-than: 80
          generate-workflow-summary: true
          workflow-summary-heading: JaCoCo Test Coverage Summary
          generate-coverage-endpoint: true
          generate-coverage-badge: true
          coverage-badge-filename: jacoco.svg

      - name: Log coverage percentage
        run: |
          coverage=$(echo "${{ steps.jacoco.outputs.coverage }} * 100" | bc)
          branches=$(echo "${{ steps.jacoco.outputs.branches }} * 100" | bc)
          echo "Coverage = ${coverage}%"
          echo "Branch Coverage = ${branches}%"

      - name: Upload JaCoCo badge
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-badge
          path: .github/badges/jacoco.svg

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Push coverage badge to gh-pages
        run: |
          mkdir -p public
          cp path/to/generated-badge.svg public/coverage-badge.svg
          git fetch
          git switch gh-pages || git checkout --orphan gh-pages
          mv public/* .
          git add -A
          git commit -m "Update coverage badge [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
