name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Run tests and generate coverage report
        run: |
          mvn -Dtest.quiet=true -Dmaven.test.redirectTestOutputToFile=true clean test org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report --quiet
          if [ -f target/site/jacoco/jacoco.xml ]; then
            echo "Coverage report generated successfully."
          else
            echo "Coverage report not found. Failing the build."
            exit 1
          fi

      - name: Display test results summary
        run: |
          echo "=== Test Results Summary ==="
          TESTS_RUN=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -ho 'tests="[0-9]*"' {} \; | grep -o '[0-9]*' | awk '{sum += $1} END {print sum}')
          FAILURES=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -ho 'failures="[0-9]*"' {} \; | grep -o '[0-9]*' | awk '{sum += $1} END {print sum}')
          ERRORS=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -ho 'errors="[0-9]*"' {} \; | grep -o '[0-9]*' | awk '{sum += $1} END {print sum}')
          SKIPPED=$(find target/surefire-reports -name "TEST-*.xml" -exec grep -ho 'skipped="[0-9]*"' {} \; | grep -o '[0-9]*' | awk '{sum += $1} END {print sum}')
          echo "Tests Run: $TESTS_RUN"
          echo "Failures: $FAILURES"
          echo "Errors: $ERRORS"
          echo "Skipped: $SKIPPED"

      - name: Calculate and display coverage
        run: |
          echo "=== Coverage Summary ==="

          # Extrair cobertura total do projeto
          total_covered=$(grep -oP '(?<=<counter type="LINE" covered=")\d+' target/site/jacoco/jacoco.xml | tail -1)
          total_missed=$(grep -oP '(?<=<counter type="LINE" missed=")\d+' target/site/jacoco/jacoco.xml | tail -1)

          if [ -n "$total_covered" ] && [ -n "$total_missed" ]; then
            total=$((total_covered + total_missed))
            coverage=$(echo "scale=2; ($total_covered / $total) * 100" | bc)
            echo "Total Line Coverage: ${coverage}% (${total_covered}/${total} lines)"
          else
            echo "Could not calculate coverage"
          fi