name: Java DEV CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - DdCaCf8g-ImproveCiCd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Build with Maven
        run: mvn -B test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v3
        with:
          colors: '#4c1 #97ca00 #a4a61d #dfb317 #fe7d37 #e05d44'
          fail-if-coverage-less-than: 80
          generate-workflow-summary: true
          workflow-summary-heading: JaCoCo Test Coverage Summary

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit the badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Douglas019BR'
            git config --global user.email 'douglassermarini@gmail.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge [skip ci]"
            git push
          fi

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/
